import type { CaseManifest, ConformanceCase, DependencyName } from "../controller/runner.ts";

export type ProbeKind =
  | "https"
  | "redirect"
  | "raw-http1"
  | "raw-http2"
  | "fault"
  | "revocation"
  | "confidentiality"
  | "bypass";

export interface Stage1CaseDefinition extends ConformanceCase {
  probe: Readonly<{
    kind: ProbeKind;
    scenario: string;
    expected: "allow" | "deny" | "safe" | "drain" | "redacted";
    positiveControl?: string;
  }>;
}

const dependencies = (...values: DependencyName[]): readonly DependencyName[] => values;
const candidateProfiles = ["insecure-container", "linux-kvm"] as const;

const define = (
  id: string,
  group: ConformanceCase["group"],
  kind: ProbeKind,
  scenario: string,
  expected: Stage1CaseDefinition["probe"]["expected"],
  requiredDependencies: readonly DependencyName[],
  positiveControl?: string,
  timeout = 45_000,
): Stage1CaseDefinition =>
  Object.freeze({
    id,
    group,
    timeout_ms: timeout,
    profiles: [...candidateProfiles],
    dependencies: [...requiredDependencies],
    probe: Object.freeze({ kind, scenario, expected, ...(positiveControl ? { positiveControl } : {}) }),
  });

const identity = dependencies("identity");
const authorized = dependencies("identity", "authorization", "audit");
const revoked = dependencies("identity", "authorization", "audit", "revocation");

export const STAGE_1_CASES: readonly Stage1CaseDefinition[] = Object.freeze([
  define("identity.capability-valid", "identity-route", "https", "capability-valid", "allow", identity),
  define(
    "identity.capability-missing",
    "identity-route",
    "https",
    "capability-missing",
    "deny",
    identity,
    "identity.capability-valid",
  ),
  define(
    "identity.capability-malformed",
    "identity-route",
    "https",
    "capability-malformed",
    "deny",
    identity,
    "identity.capability-valid",
  ),
  define(
    "identity.capability-expired",
    "identity-route",
    "https",
    "capability-expired",
    "deny",
    identity,
    "identity.capability-valid",
  ),
  define(
    "identity.capability-other-session",
    "identity-route",
    "https",
    "capability-other-session",
    "deny",
    identity,
    "identity.capability-valid",
  ),
  define("route.allowed-host-port", "identity-route", "https", "allowed-host-port", "allow", authorized),
  define(
    "route.undeclared-host",
    "identity-route",
    "https",
    "undeclared-host",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define(
    "route.direct-destination-ip",
    "identity-route",
    "https",
    "direct-destination-ip",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define(
    "route.alternate-port",
    "identity-route",
    "https",
    "alternate-port",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define(
    "route.wrong-method",
    "identity-route",
    "https",
    "wrong-method",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define("route.wrong-path", "identity-route", "https", "wrong-path", "deny", authorized, "route.allowed-host-port"),
  define(
    "route.encoded-slash-dot",
    "identity-route",
    "https",
    "encoded-slash-dot",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define("route.traversal", "identity-route", "https", "traversal", "deny", authorized, "route.allowed-host-port"),
  define(
    "route.redirect-undeclared",
    "identity-route",
    "redirect",
    "redirect-undeclared",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define(
    "route.connect-host-mismatch",
    "identity-route",
    "raw-http1",
    "connect-host-mismatch",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define(
    "route.sni-host-mismatch",
    "identity-route",
    "raw-http1",
    "sni-host-mismatch",
    "deny",
    authorized,
    "route.allowed-host-port",
  ),
  define(
    "route.http2-authority-mismatch",
    "identity-route",
    "raw-http2",
    "authority-mismatch",
    "deny",
    authorized,
    "parser.http2-valid",
  ),

  define("parser.http1-valid", "http-parsing", "raw-http1", "valid", "allow", authorized),
  define(
    "parser.cl-te-conflict",
    "http-parsing",
    "raw-http1",
    "cl-te-conflict",
    "deny",
    authorized,
    "parser.http1-valid",
  ),
  define(
    "parser.duplicate-host",
    "http-parsing",
    "raw-http1",
    "duplicate-host",
    "deny",
    authorized,
    "parser.http1-valid",
  ),
  define(
    "parser.duplicate-authorization",
    "http-parsing",
    "raw-http1",
    "duplicate-authorization",
    "safe",
    authorized,
    "parser.http1-valid",
  ),
  define(
    "parser.duplicate-proxy-authorization",
    "http-parsing",
    "raw-http1",
    "duplicate-proxy-authorization",
    "deny",
    authorized,
    "parser.http1-valid",
  ),
  define("parser.absolute-form", "http-parsing", "raw-http1", "absolute-form", "allow", authorized),
  define(
    "parser.origin-form-to-proxy",
    "http-parsing",
    "raw-http1",
    "origin-form-to-proxy",
    "deny",
    authorized,
    "parser.absolute-form",
  ),
  define(
    "parser.ambiguous-whitespace",
    "http-parsing",
    "raw-http1",
    "ambiguous-whitespace",
    "safe",
    authorized,
    "parser.http1-valid",
  ),
  define("parser.obs-fold", "http-parsing", "raw-http1", "obs-fold", "safe", authorized, "parser.http1-valid"),
  define(
    "parser.oversized-header",
    "http-parsing",
    "raw-http1",
    "oversized-header",
    "deny",
    authorized,
    "parser.http1-valid",
  ),
  define(
    "parser.oversized-request-line",
    "http-parsing",
    "raw-http1",
    "oversized-request-line",
    "deny",
    authorized,
    "parser.http1-valid",
  ),
  define(
    "parser.invalid-chunk-size",
    "http-parsing",
    "raw-http1",
    "invalid-chunk-size",
    "deny",
    authorized,
    "parser.http1-valid",
  ),
  define(
    "parser.invalid-chunk-extension",
    "http-parsing",
    "raw-http1",
    "invalid-chunk-extension",
    "safe",
    authorized,
    "parser.http1-valid",
  ),
  define(
    "parser.path-normalization",
    "http-parsing",
    "raw-http1",
    "path-normalization",
    "deny",
    authorized,
    "parser.http1-valid",
  ),
  define("parser.http2-valid", "http-parsing", "raw-http2", "valid", "allow", authorized),
  define(
    "parser.http2-duplicate-pseudo",
    "http-parsing",
    "raw-http2",
    "duplicate-pseudo",
    "deny",
    authorized,
    "parser.http2-valid",
  ),
  define(
    "parser.http2-reordered-pseudo",
    "http-parsing",
    "raw-http2",
    "reordered-pseudo",
    "deny",
    authorized,
    "parser.http2-valid",
  ),
  define(
    "parser.http2-invalid-pseudo",
    "http-parsing",
    "raw-http2",
    "invalid-pseudo",
    "deny",
    authorized,
    "parser.http2-valid",
  ),
  define(
    "parser.http2-downgrade-ambiguity",
    "http-parsing",
    "raw-http2",
    "downgrade-ambiguity",
    "deny",
    authorized,
    "parser.http2-valid",
  ),

  define(
    "credential.placeholder-preflight",
    "credential-handling",
    "https",
    "placeholder-preflight",
    "allow",
    authorized,
  ),
  define(
    "credential.guest-authorization-stripped",
    "credential-handling",
    "https",
    "authorization-stripped",
    "allow",
    authorized,
  ),
  define("credential.bearer-injected", "credential-handling", "https", "bearer", "allow", authorized),
  define("credential.api-key-injected", "credential-handling", "https", "api-key", "allow", authorized),
  define("credential.basic-injected", "credential-handling", "https", "basic", "allow", authorized),
  define(
    "credential.secret-absent",
    "credential-handling",
    "fault",
    "secret-absent",
    "deny",
    authorized,
    "credential.bearer-injected",
  ),
  define(
    "credential.secret-revoked",
    "credential-handling",
    "revocation",
    "secret-revoked",
    "deny",
    revoked,
    "credential.bearer-injected",
  ),
  define("credential.no-leak", "credential-handling", "confidentiality", "all-sinks", "redacted", authorized),

  define(
    "bypass.unset-proxy",
    "bypass-resistance",
    "bypass",
    "unset-proxy",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.direct-ipv4",
    "bypass-resistance",
    "bypass",
    "direct-ipv4",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.direct-ipv6",
    "bypass-resistance",
    "bypass",
    "direct-ipv6",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.arbitrary-dns",
    "bypass-resistance",
    "bypass",
    "arbitrary-dns",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.dns-over-https",
    "bypass-resistance",
    "bypass",
    "dns-over-https",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.udp-quic",
    "bypass-resistance",
    "bypass",
    "udp-quic",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.alternate-tcp",
    "bypass-resistance",
    "bypass",
    "alternate-tcp",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.nested-connect",
    "bypass-resistance",
    "bypass",
    "nested-connect",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.websocket",
    "bypass-resistance",
    "bypass",
    "websocket",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.cogs-api",
    "bypass-resistance",
    "bypass",
    "cogs-api",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.proxy-admin",
    "bypass-resistance",
    "bypass",
    "proxy-admin",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.openbao",
    "bypass-resistance",
    "bypass",
    "openbao",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),
  define(
    "bypass.cloud-metadata",
    "bypass-resistance",
    "bypass",
    "cloud-metadata",
    "deny",
    dependencies("network_enforcement"),
    "route.allowed-host-port",
  ),

  define("audit.intent-before-use", "audit-failure", "https", "intent-before-use", "allow", authorized),
  define(
    "audit.wal-unwritable",
    "audit-failure",
    "fault",
    "audit-unwritable",
    "deny",
    authorized,
    "audit.intent-before-use",
  ),
  define("audit.wal-full", "audit-failure", "fault", "audit-full", "deny", authorized, "audit.intent-before-use"),
  define(
    "audit.authorization-outage",
    "audit-failure",
    "fault",
    "authorization-outage",
    "deny",
    authorized,
    "audit.intent-before-use",
  ),
  define(
    "audit.telemetry-outage-uncredentialed",
    "audit-failure",
    "fault",
    "telemetry-outage",
    "allow",
    dependencies("authorization", "audit"),
  ),
  define("audit.completion-correlated", "audit-failure", "https", "completion-correlated", "allow", authorized),
  define(
    "audit.central-metadata-only",
    "audit-failure",
    "confidentiality",
    "central-metadata-only",
    "redacted",
    authorized,
  ),

  define(
    "revocation.signal-denies-new",
    "revocation",
    "revocation",
    "deny-new",
    "deny",
    revoked,
    "credential.bearer-injected",
  ),
  define(
    "revocation.direct-store-change",
    "revocation",
    "revocation",
    "direct-store-change",
    "deny",
    revoked,
    "credential.bearer-injected",
  ),
  define(
    "revocation.long-lived-drain",
    "revocation",
    "revocation",
    "long-lived-drain",
    "drain",
    revoked,
    "credential.bearer-injected",
    60_000,
  ),
  define("revocation.replacement-capability", "revocation", "revocation", "replacement-capability", "allow", revoked),
  define(
    "revocation.old-capability-invalid",
    "revocation",
    "revocation",
    "old-capability-invalid",
    "deny",
    revoked,
    "revocation.replacement-capability",
  ),
]);

export const STAGE_1_MANIFEST: CaseManifest = {
  version: "cogs.egress-cases/v1alpha1",
  cases: STAGE_1_CASES.map(({ probe: _probe, ...test }) => Object.freeze(test)),
};
Object.freeze(STAGE_1_MANIFEST.cases);
Object.freeze(STAGE_1_MANIFEST);

export function stage1Case(id: string): Stage1CaseDefinition {
  const found = STAGE_1_CASES.find((test) => test.id === id);
  if (!found) throw new Error(`unknown Stage 1 case: ${id}`);
  return found;
}
