"""One closed command identity vocabulary for the Stage 2 Kata owners."""
from enum import Enum


class CommandId(Enum):
    IP_NETNS_ADD = "IP_NETNS_ADD"
    IP_LINK_ADD = "IP_LINK_ADD"
    IP_LINK_MOVE = "IP_LINK_MOVE"
    IP_VETH_ADD_ATOMIC = "IP_VETH_ADD_ATOMIC"
    IP_HOST_ADDRESS_ADD = "IP_HOST_ADDRESS_ADD"
    IP_HOST_ADDRGEN_NONE = "IP_HOST_ADDRGEN_NONE"
    IP_HOST_LINK_UP = "IP_HOST_LINK_UP"
    IP_PEER_RENAME = "IP_PEER_RENAME"
    IP_PEER_ADDRGEN_NONE = "IP_PEER_ADDRGEN_NONE"
    IP_LOOPBACK_UP = "IP_LOOPBACK_UP"
    IP_GUEST_ADDRESS_ADD = "IP_GUEST_ADDRESS_ADD"
    IP_GUEST_LINK_UP = "IP_GUEST_LINK_UP"
    IP_HOST_LINK_REMOVE = "IP_HOST_LINK_REMOVE"
    IP_NETNS_REMOVE = "IP_NETNS_REMOVE"
    IP_HOST_LINKS = "IP_HOST_LINKS"
    IP_HOST_ADDRESSES = "IP_HOST_ADDRESSES"
    IP_HOST_ROUTES4 = "IP_HOST_ROUTES4"
    IP_HOST_ROUTES6 = "IP_HOST_ROUTES6"
    IP_NS_LINKS = "IP_NS_LINKS"
    IP_NS_ADDRESSES = "IP_NS_ADDRESSES"
    IP_NS_ROUTES4 = "IP_NS_ROUTES4"
    IP_NS_ROUTES6 = "IP_NS_ROUTES6"
    IP_NETNS_LIST = "IP_NETNS_LIST"
    IP_ALL_LINKS = "IP_ALL_LINKS"
    IP_ALL_ADDRESSES = "IP_ALL_ADDRESSES"
    IP_ALL_ROUTES4 = "IP_ALL_ROUTES4"
    IP_ALL_ROUTES6 = "IP_ALL_ROUTES6"
    TC_QDISC = "TC_QDISC"
    TC_INGRESS_FILTER = "TC_INGRESS_FILTER"
    NFT_INSTALL = "NFT_INSTALL"
    NFT_INSTALL_OWNED = "NFT_INSTALL_OWNED"
    NFT_REMOVE = "NFT_REMOVE"
    NFT_REMOVE_ATOMIC = "NFT_REMOVE_ATOMIC"
    NFT_TABLE = "NFT_TABLE"
    NFT_RULESET = "NFT_RULESET"
    SSH_KEYGEN_CLIENT = "SSH_KEYGEN_CLIENT"
    SSH_KEYGEN_SERVER = "SSH_KEYGEN_SERVER"
    SSH_PUBLIC_CLIENT = "SSH_PUBLIC_CLIENT"
    SSH_PUBLIC_SERVER = "SSH_PUBLIC_SERVER"
    CONTAINERD_START = "CONTAINERD_START"
    CTR_RUN = "CTR_RUN"
    CTR_CONTAINER_INFO = "CTR_CONTAINER_INFO"
    CTR_CONTAINER_LIST = "CTR_CONTAINER_LIST"
    CTR_TASK_LIST = "CTR_TASK_LIST"
    CTR_TASK_TERM = "CTR_TASK_TERM"
    CTR_TASK_KILL = "CTR_TASK_KILL"
    CTR_TASK_REMOVE = "CTR_TASK_REMOVE"
    CTR_CONTAINER_REMOVE = "CTR_CONTAINER_REMOVE"
    SSH_READY = "SSH_READY"

    # Compatibility spellings are aliases of the same canonical members, not a
    # second action vocabulary.
    NETNS_ADD = IP_NETNS_ADD
    LINK_ADD = IP_LINK_ADD
    LINK_MOVE = IP_LINK_MOVE
    HOST_ADDRESS_ADD = IP_HOST_ADDRESS_ADD
    HOST_ADDRGEN_NONE = IP_HOST_ADDRGEN_NONE
    HOST_LINK_UP = IP_HOST_LINK_UP
    PEER_RENAME = IP_PEER_RENAME
    PEER_ADDRGEN_NONE = IP_PEER_ADDRGEN_NONE
    LOOPBACK_UP = IP_LOOPBACK_UP
    GUEST_ADDRESS_ADD = IP_GUEST_ADDRESS_ADD
    GUEST_LINK_UP = IP_GUEST_LINK_UP
    HOST_LINK_REMOVE = IP_HOST_LINK_REMOVE
    NETNS_REMOVE = IP_NETNS_REMOVE
    HOST_LINKS = IP_HOST_LINKS
    HOST_ADDRESSES = IP_HOST_ADDRESSES
    HOST_ROUTES4 = IP_HOST_ROUTES4
    HOST_ROUTES6 = IP_HOST_ROUTES6
    NS_LINKS = IP_NS_LINKS
    NS_ADDRESSES = IP_NS_ADDRESSES
    NS_ROUTES4 = IP_NS_ROUTES4
    NS_ROUTES6 = IP_NS_ROUTES6
    QDISC = TC_QDISC
    INGRESS_FILTER = TC_INGRESS_FILTER


COMMAND_IDS = frozenset(item.value for item in CommandId)
NETWORK_COMMANDS = frozenset(item for item in CommandId if item.value.startswith(("IP_", "TC_", "NFT_")))
RUNTIME_COMMANDS = frozenset(
    item for item in CommandId
    if item is CommandId.CONTAINERD_START or item.value.startswith("CTR_")
)
